;; font-lock-constant
;; font-lock-function
;; font-lock-keyword
;; font-lock-builtin
;; font-lock-variable-name
;; font-lock-warning
;; font-lock-string
;; font-lock-preprocessor




    (define-generic-mode
      'gvpr-mode                      ;; name of the mode
      '("//")                         ;; comments
      '(                              ;; keywords
         "void" "int" "char" "float" "long" "unsigned" "double" "string" "node_t" "edge_t" "graph_t" "obj_t"
         "if" "else" "for" "forr" "while" "switch" "case" "break" "continue" "return"
      )
      '(
                                      ;; clauses
         ("\\<BEGIN\\>"   . 'font-lock-preprocessor-face)
         ("\\<BEGIN_G\\>" . 'font-lock-preprocessor-face)
         ("\\<N\\>"       . 'font-lock-preprocessor-face)
         ("\\<E\\>"       . 'font-lock-preprocessor-face)
         ("\\<END_G\\>"   . 'font-lock-preprocessor-face)
         ("\\<END\\>"     . 'font-lock-preprocessor-face)

                                      ;; operators
         ("--" . 'font-lock-constant-face)
         ("->" . 'font-lock-constant-face)
         ("==" . 'font-lock-constant-face)
         ("!=" . 'font-lock-constant-face)
         ("+"  . 'font-lock-constant-face)
         ("-"  . 'font-lock-constant-face)
         ("*"  . 'font-lock-constant-face)
         ("/"  . 'font-lock-constant-face)
         ("="  . 'font-lock-constant-face)
         ("<"  . 'font-lock-constant-face)
         (">"  . 'font-lock-constant-face)
         ("<=" . 'font-lock-constant-face)
         (">=" . 'font-lock-constant-face)
         ("#"  . 'font-lock-constant-face)
         ("\\<in\\>" . 'font-lock-constant-face)

                                      ;; common attributes
         ("\\<head\\>"      . 'font-lock-builtin-face)
         ("\\<tail\\>"      . 'font-lock-builtin-face)
         ("\\<name\\>"      . 'font-lock-builtin-face)
         ("\\<indegree\\>"  . 'font-lock-builtin-face)
         ("\\<outdegree\\>" . 'font-lock-builtin-face)
         ("\\<degree\\>"    . 'font-lock-builtin-face)
         ("\\<root\\>"      . 'font-lock-builtin-face)
         ("\\<parent\\>"    . 'font-lock-builtin-face)
         ("\\<n_edges\\>"   . 'font-lock-builtin-face)
         ("\\<n_nodes\\>"   . 'font-lock-builtin-face)
         ("\\<directed\\>"  . 'font-lock-builtin-face)
         ("\\<strict\\>"    . 'font-lock-builtin-face)

                                      ;; built-in functions
         ("\\<graph\\>"       . 'font-lock-builtin-face)
         ("\\<sugb\\>"        . 'font-lock-builtin-face)
         ("\\<isSubg\\>"      . 'font-lock-builtin-face)
         ("\\<fstsubg\\>"     . 'font-lock-builtin-face)
         ("\\<nxtsugb\\>"     . 'font-lock-builtin-face)
         ("\\<isDirect\\>"    . 'font-lock-builtin-face)
         ("\\<isStrict\\>"    . 'font-lock-builtin-face)
         ("\\<nNodes\\>"      . 'font-lock-builtin-face)
         ("\\<nEdges\\>"      . 'font-lock-builtin-face)
         ("\\<node\\>"        . 'font-lock-builtin-face)
         ("\\<subnode\\>"     . 'font-lock-builtin-face)
         ("\\<fstnode\\>"     . 'font-lock-builtin-face)
         ("\\<nxtnode\\>"     . 'font-lock-builtin-face)
         ("\\<isNode\\>"      . 'font-lock-builtin-face)
         ("\\<isSubnode\\>"   . 'font-lock-builtin-face)
         ("\\<indegreeOf\\>"  . 'font-lock-builtin-face)
         ("\\<outdegreeOf\\>" . 'font-lock-builtin-face)
         ("\\<degreeOf\\>"    . 'font-lock-builtin-face)
         ("\\<edge\\>"        . 'font-lock-builtin-face)
         ("\\<edge_sg\\>"     . 'font-lock-builtin-face)
         ("\\<subedge\\>"     . 'font-lock-builtin-face)
         ("\\<isEdge\\>"      . 'font-lock-builtin-face)
         ("\\<isSubedge\\>"   . 'font-lock-builtin-face)
         ("\\<fstout\\>"      . 'font-lock-builtin-face)
         ("\\<fstout_sg\\>"   . 'font-lock-builtin-face)
         ("\\<nxtout\\>"      . 'font-lock-builtin-face)
         ("\\<nxtout_sg\\>"   . 'font-lock-builtin-face)
         ("\\<fstin\\>"       . 'font-lock-builtin-face)
         ("\\<fstin_sg\\>"    . 'font-lock-builtin-face)
         ("\\<nxtin\\>"       . 'font-lock-builtin-face)
         ("\\<nxtin_sg\\>"    . 'font-lock-builtin-face)
         ("\\<fstedge\\>"     . 'font-lock-builtin-face)
         ("\\<nxtedge\\>"     . 'font-lock-builtin-face)
         ("\\<opp\\>"         . 'font-lock-builtin-face)
         ("\\<write\\>"       . 'font-lock-builtin-face)
         ("\\<writeG\\>"      . 'font-lock-builtin-face)
         ("\\<fwriteG\\>"     . 'font-lock-builtin-face)
         ("\\<readG\\>"       . 'font-lock-builtin-face)
         ("\\<freadG\\>"      . 'font-lock-builtin-face)
         ("\\<delete\\>"      . 'font-lock-builtin-face)
         ("\\<isIn\\>"        . 'font-lock-builtin-face)
         ("\\<cloneG\\>"      . 'font-lock-builtin-face)
         ("\\<clone\\>"       . 'font-lock-builtin-face)
         ("\\<copy\\>"        . 'font-lock-builtin-face)
         ("\\<copyA\\>"       . 'font-lock-builtin-face)
         ("\\<induce\\>"      . 'font-lock-builtin-face)
         ("\\<hasAttr\\>"     . 'font-lock-builtin-face)
         ("\\<isAttr\\>"      . 'font-lock-builtin-face)
         ("\\<aget\\>"        . 'font-lock-builtin-face)
         ("\\<aset\\>"        . 'font-lock-builtin-face)
         ("\\<getDflt\\>"     . 'font-lock-builtin-face)
         ("\\<setDflt\\>"     . 'font-lock-builtin-face)
         ("\\<fstAttr\\>"     . 'font-lock-builtin-face)
         ("\\<nxtAttr\\>"     . 'font-lock-builtin-face)
         ("\\<copmOf\\>"      . 'font-lock-builtin-face)
         ("\\<kindOf\\>"      . 'font-lock-builtin-face)
         ("\\<lock\\>"        . 'font-lock-builtin-face)
         ("\\<sprintf\\>"     . 'font-lock-builtin-face)
         ("\\<gsub\\>"        . 'font-lock-builtin-face)
         ("\\<sub\\>"         . 'font-lock-builtin-face)
         ("\\<substr\\>"      . 'font-lock-builtin-face)
         ("\\<strcmp\\>"      . 'font-lock-builtin-face)
         ("\\<length\\>"      . 'font-lock-builtin-face)
         ("\\<index\\>"       . 'font-lock-builtin-face)
         ("\\<rindex\\>"      . 'font-lock-builtin-face)
         ("\\<match\\>"       . 'font-lock-builtin-face)
         ("\\<toupper\\>"     . 'font-lock-builtin-face)
         ("\\<tolower\\>"     . 'font-lock-builtin-face)
         ("\\<canon\\>"       . 'font-lock-builtin-face)
         ("\\<html\\>"        . 'font-lock-builtin-face)
         ("\\<ishtml\\>"      . 'font-lock-builtin-face)
         ("\\<xOf\\>"         . 'font-lock-builtin-face)
         ("\\<yOf\\>"         . 'font-lock-builtin-face)
         ("\\<llOf\\>"        . 'font-lock-builtin-face)
         ("\\<urOf\\>"        . 'font-lock-builtin-face)
         ("\\<sscanf\\>"      . 'font-lock-builtin-face)
         ("\\<split\\>"       . 'font-lock-builtin-face)
         ("\\<tokens\\>"      . 'font-lock-builtin-face)
         ("\\<print\\>"       . 'font-lock-builtin-face)
         ("\\<printf\\>"      . 'font-lock-builtin-face)
         ("\\<scanf\\>"       . 'font-lock-builtin-face)
         ("\\<openF\\>"       . 'font-lock-builtin-face)
         ("\\<closeF\\>"      . 'font-lock-builtin-face)
         ("\\<readL\\>"       . 'font-lock-builtin-face)
         ("\\<exp\\>"         . 'font-lock-builtin-face)
         ("\\<log\\>"         . 'font-lock-builtin-face)
         ("\\<sqrt\\>"        . 'font-lock-builtin-face)
         ("\\<pow\\>"         . 'font-lock-builtin-face)
         ("\\<cos\\>"         . 'font-lock-builtin-face)
         ("\\<sin\\>"         . 'font-lock-builtin-face)
         ("\\<atan2\\>"       . 'font-lock-builtin-face)
         ("\\<MIN\\>"         . 'font-lock-builtin-face)
         ("\\<MAX\\>"         . 'font-lock-builtin-face)
         ("\\<unset\\>"       . 'font-lock-builtin-face)
         ("\\<exit\\>"        . 'font-lock-builtin-face)
         ("\\<system\\>"      . 'font-lock-builtin-face)
         ("\\<rand\\>"        . 'font-lock-builtin-face)
         ("\\<srand\\>"       . 'font-lock-builtin-face)
         ("\\<colorx\\>"      . 'font-lock-builtin-face)

                                      ;; built-in variables
         ("\\<$\\>"        . 'font-lock-builtin-face)
         ("\\<$F\\>"       . 'font-lock-builtin-face)
         ("\\<$G\\>"       . 'font-lock-builtin-face)
         ("\\<$NG\\>"      . 'font-lock-builtin-face)
         ("\\<$O\\>"       . 'font-lock-builtin-face)
         ("\\<$T\\>"       . 'font-lock-builtin-face)
         ("\\<$trgname\\>" . 'font-lock-builtin-face)
         ("\\<$tvroot\\>"  . 'font-lock-builtin-face)
         ("\\<$tvnext\\>"  . 'font-lock-builtin-face)
         ("\\<$tvnext\\>"  . 'font-lock-builtin-face)
         ("\\<$tvedge\\>"  . 'font-lock-builtin-face)
         ("\\<$tvtype\\>"  . 'font-lock-builtin-face)
         ("\\<ARGC\\>"     . 'font-lock-builtin-face)
         ("\\<ARGV\\>"     . 'font-lock-builtin-face)

                                      ;; built-in constants
         ("\\<NULL\\>"          . 'font-lock-builtin-face)
         ("\\<TV_flat\\>"       . 'font-lock-builtin-face)
         ("\\<TV_ne\\>"         . 'font-lock-builtin-face)
         ("\\<TV_en\\>"         . 'font-lock-builtin-face)
         ("\\<TV_dfs\\>"        . 'font-lock-builtin-face)
         ("\\<TV_postdfs\\>"    . 'font-lock-builtin-face)
         ("\\<TV_prepostdfs\\>" . 'font-lock-builtin-face)
         ("\\<TV_fwd\\>"        . 'font-lock-builtin-face)
         ("\\<TV_postfwd\\>"    . 'font-lock-builtin-face)
         ("\\<TV_prepostfwd\\>" . 'font-lock-builtin-face)
         ("\\<TV_rev\\>"        . 'font-lock-builtin-face)
         ("\\<TV_postrev\\>"    . 'font-lock-builtin-face)
         ("\\<TV_prepostrev\\>" . 'font-lock-builtin-face)
         ("\\<TV_bfs\\>"        . 'font-lock-builtin-face)

      )
      '("\\.gvpr$")                   ;; files for which to activate this mode
       nil                            ;; other functions
      "A basic mode for gvpr scripts" ;; doc string
      )
